// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using luizalabs.desafio_tecnico.Data;

#nullable disable

namespace luizalabs.desafio_tecnico.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("luizalabs.desafio_tecnico.Models.Legacy.LegacyData", b =>
                {
                    b.Property<Guid>("request_line_id")
                        .HasColumnType("char(36)");

                    b.Property<int>("line")
                        .HasColumnType("int");

                    b.Property<DateTime>("order_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("order_id")
                        .HasColumnType("int");

                    b.Property<int>("product_id")
                        .HasColumnType("int");

                    b.Property<float>("product_value")
                        .HasColumnType("float");

                    b.Property<Guid>("request_id")
                        .HasColumnType("char(36)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("request_line_id");

                    b.ToTable("requests_lines", (string)null);
                });

            modelBuilder.Entity("luizalabs.desafio_tecnico.Models.Legacy.LegacyFile", b =>
                {
                    b.Property<Guid>("request_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("total_lines")
                        .HasColumnType("int");

                    b.HasKey("request_id");

                    b.ToTable("requests", (string)null);
                });

            modelBuilder.Entity("luizalabs.desafio_tecnico.Models.Legacy.LegacyData", b =>
                {
                    b.HasOne("luizalabs.desafio_tecnico.Models.Legacy.LegacyFile", "file")
                        .WithMany("Lines")
                        .HasForeignKey("request_line_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("file");
                });

            modelBuilder.Entity("luizalabs.desafio_tecnico.Models.Legacy.LegacyFile", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
